name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dummy-test:
    steps:
      - name: dummy test command
        run: echo "CI dummy-test"
  docker-image:
    uses: ./.github/workflows/docker.yaml
    #  secrets:
    #    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #    DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}